### Login oikealla salasanalla
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
  "username": "juha",
  "password": "salasana"
}

### Login väärällä salasanalla
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
  "username": "juha",
  "password": "salasana-väärä"
}
